[package]
name = "cargo-sorty"
version = "0.1.0"
authors = ["Ray Solomon <raybsolomon@gmail.com>",
           "arcnmx",
           "Jurica Bradaric <jbradaric@gmail.com"
          ]
license = "MIT"
readme = "README.md"

[dependencies.sorty]
git = "https://github.com/Wafflespeanut/rust-sorty"
